CREATE TABLE IF NOT EXISTS 'business' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'name' TEXT NOT NULL ,
'address' TEXT NOT NULL ,
'city' TEXT NOT NULL ,
'state' TEXT NOT NULL ,
'postal_code' TEXT NOT NULL ,
'purchased' INTEGER
);

CREATE TABLE IF NOT EXISTS 'review' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'business_id' INTEGER NOT NULL  REFERENCES 'business' ('id'),
'user_id' INTEGER NOT NULL  REFERENCES 'user' ('id'),
'score' INTEGER NOT NULL ,
'date' INTEGER NOT NULL ,
'text' TEXT NOT NULL 
);

CREATE TABLE IF NOT EXISTS 'user' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'username' TEXT NOT NULL ,
'password_hash' TEXT NOT NULL 
);

CREATE TABLE IF NOT EXISTS 'photo' (
'id' INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
'business_id' INTEGER NOT NULL  REFERENCES 'business' ('id'),
'caption' INTEGER NOT NULL 
);

PRAGMA user_version = 1;